#!/usr/local/bin/bash -e

# This script helps to move executables to another system.
# This script copys an executable and it's needed libraries to the current directory.
# Furthermore it alters the binaries rpath to match the new library locations.
# You should ALWAYS check the generated executables with "ldd"

cp "$(which ${1})" .
PROG=$(basename "${1}")
mkdir -p ./lib

#use ldd to resolve the libs and use `patchelf --print-needed to filter out
# "magic" libs kernel-interfacing libs such as linux-vdso.so, ld-linux-x86-65.so or libpthread
# which you probably should not relativize anyway
# and copy the lib selection to ./lib
for l in $(join <(ldd "${PROG}" | awk '{if(substr($3,0,1)=="/") print $1,$3}' | sort) \
    <(patchelf --print-needed "$PROG" | sort) | cut -d\  -f2) 
    do 
        cp ${l} lib/ 
    done

#make the relative lib paths override the system lib path
patchelf --set-rpath "\$ORIGIN/lib" "${PROG}"
