#!/bin/csh
#opnsense-cloudinit workaround

#usage
#echo /root/opnsense-cloudinit/opnsense-cloudinit > /usr/local/etc/rc.syshook.d/start/99-cloudinit
#chmod +x /usr/local/etc/rc.syshook.d/start/99-cloudinit 

set PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin
export $PATH

#disk_resize
gpart recover vtbd0
gpart resize -i 2 vtbd0
growfs -y vtbd0p2

#set_key
set sshkey=`fetch http://169.254.169.254/openstack/latest/meta_data.json -q -o - | /root/opnsense-cloudinit/jq -r '.keys[] |.data' | /root/opnsense-cloudinit/base64 | sed 's/ //g`
sed -i '' -e "s/<authorizedkeys>.*<\/authorizedkeys>/<authorizedkeys>$sshkey<\/authorizedkeys>/g" /conf/config.xml

#set_hostname
set fqdn=`fetch http://169.254.169.254/openstack/latest/meta_data.json -q -o - | /root/opnsense-cloudinit/jq '.hostname' | sed 's/.novalocal//g'`
sed -i "" "s/hostname.*/hostname=$fqdn/g" /etc/rc.conf
hostname `echo $fqdn | tr -d '"'`
sed -i '' -e "s/<hostname>.*<\/hostname>/<hostname>$fqdn<\/hostname>/g" /conf/config.xml

#run userdata
fetch http://169.254.169.254/latest/user-data -q -o - | sh

#make clean
set history = 0
ssh-keygen -A

#remove opnsense-cloudinit
rm -f "/usr/local/etc/rc.syshook.d/start/99-cloudinit"
rm -f -r /root/opnsense-cloudinit

#do reboot
reboot
